# Generated by Django 5.1.2 on 2024-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, default='default_food_img.jpg', null=True, upload_to='images'),
        ),
    ]
